[[dolphindb_lib]]
arch = "x86_64"
git-tree-sha1 = "07df958362d47207df78a7fd1db08c686966c5bf"
os = "windows"

    [[dolphindb_lib.download]]
    sha256 = "465662232fb75cd2e27b82746f15c02aec1f807ec8ab09a10592f864926cde86"
    url = "https://github.com/linanisyugioh/dolphindb.jl/releases/download/v1.0.0/dolphindb_windows_x64.tar.gz"
[[dolphindb_lib]]
arch = "x86_64"
git-tree-sha1 = "06050c2ee9022a376a9b09a62451306195dbc711"
libc = "glibc"
os = "linux"

    [[dolphindb_lib.download]]
    sha256 = "b4ef19676c190b41ece6f874feb65c85bcd13b202886282bd7afc102d577b774"
    url = "https://github.com/linanisyugioh/dolphindb.jl/releases/download/v1.0.0/dolphindb_linux_x64.tar.gz"
